name: Run Tests

on:
  push:
    branches:
      - ci_basic

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NODE_VERSION }}"
        
    - name: Read .nvmrc
      id: nvm
      run: echo "::set-output name=NODE_VERSION::$(cat .nvmrc)"

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test /